security:
    # https://symfony.com/doc/current/security.html#registering-the-user-hashing-passwords
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

        App\Entity\AppUser: 'auto'

    # https://symfony.com/doc/current/security.html#loading-the-user-the-user-provider
    providers:
        app_user_provider:
            entity:
                class: App\Core\Domain\Model\Aggregate\User
                property: email # React enviará el email para loguearse

    hide_user_not_found: false

    firewalls:
        dev:
            # Ensure dev tools and static assets are always allowed
            pattern: ^/(_profiler|_wdt|assets|build)/
            security: false
        login:
            pattern: ^/480project/login
            stateless: true
            user_checker: App\Auth\Infrastructure\Security\UserChecker
            json_login:
                check_path: /480project/login
                username_path: email
                password_path: password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
        refresh:
            pattern: ^/480project/token/refresh
            stateless: true
            refresh_jwt:
                check_path: /480project/token/refresh
        api:
            pattern: ^/480project(?!token/refresh)
            stateless: true
            jwt: ~

        #main:
        #    lazy: true
        #    provider: app_user_provider #El que creamos vinculado a tu Entidad users_in_memory, original
            # Activate different ways to authenticate:
            # https://symfony.com/doc/current/security.html#the-firewall

            # https://symfony.com/doc/current/security/impersonating_user.html
            # switch_user: true

    # Note: Only the *first* matching rule is applied
    access_control:
        # - { path: ^/admin, roles: ROLE_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }
        - { path: ^/480project/login,   roles: PUBLIC_ACCESS }
        - { path: ^/480project/token/refresh,   roles: PUBLIC_ACCESS }
        - { path: ^/480project,         roles: IS_AUTHENTICATED_FULLY }

when@test:
    security:
        password_hashers:
            # Password hashers are resource-intensive by design to ensure security.
            # In tests, it's safe to reduce their cost to improve performance.
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4 # Lowest possible value for bcrypt
                time_cost: 3 # Lowest possible value for argon
                memory_cost: 10 # Lowest possible value for argon
