<?php

declare(strict_types=1);

namespace App\Shared\Domain\Model;

enum ErrorCode: string
{
    // HTTP / comunes
    case BAD_REQUEST = 'BAD_REQUEST';
    case FORBIDDEN = 'FORBIDDEN';
    case NOT_FOUND = 'NOT_FOUND';
    case CONFLICT = 'CONFLICT';
    case UNEXPECTED_ERROR = 'UNEXPECTED_ERROR';
    case INVALID_UUID = 'INVALID_UUID';
    case PAYLOAD_VALIDATION_FAILED = 'PAYLOAD_VALIDATION_FAILED';
    case INVALID_PAYLOAD = 'INVALID_PAYLOAD';

    // VO comunes
    case INVALID_EMAIL = 'INVALID_EMAIL';
    case INVALID_PASSWORD = 'INVALID_PASSWORD';
    case INVALID_PHONE = 'INVALID_PHONE';
    case INVALID_URL = 'INVALID_URL';

    // USER
    case INVALID_USER_ID = 'INVALID_USER_ID';
    case USER_NOT_FOUND = 'USER_NOT_FOUND';
    case DUPLICATED_USER_EMAIL = 'DUPLICATED_USER_EMAIL';
    case INVALID_USER_NAME = 'INVALID_USER_NAME';
    case INVALID_USER_SURNAME = 'INVALID_USER_SURNAME';

    // SECTOR
    case INVALID_SECTOR_ID = 'INVALID_SECTOR_ID';
    case SECTOR_NOT_FOUND = 'SECTOR_NOT_FOUND';
    case DUPLICATED_SECTOR_NAME = 'DUPLICATED_SECTOR_NAME';
    case INVALID_SECTOR_NAME = 'INVALID_SECTOR_NAME';

    // TECHNOLOGY
    case INVALID_TECHNOLOGY_ID = 'INVALID_TECHNOLOGY_ID';
    case TECHNOLOGY_NOT_FOUND = 'TECHNOLOGY_NOT_FOUND';
    case DUPLICATED_TECHNOLOGY_NAME = 'DUPLICATED_TECHNOLOGY_NAME';
    case INVALID_TECHNOLOGY_NAME = 'INVALID_TECHNOLOGY_NAME';

    // PROJECT_ROLE
    case INVALID_PROJECT_ROLE_ID = 'INVALID_PROJECT_ROLE_ID';
    case PROJECT_ROLE_NOT_FOUND = 'PROJECT_ROLE_NOT_FOUND';
    case DUPLICATED_PROJECT_ROLE_NAME = 'DUPLICATED_PROJECT_ROLE_NAME';

    // REFRESH_TOKEN
    case INVALID_REFRESH_TOKEN_ID = 'INVALID_REFRESH_TOKEN_ID';
    case REFRESH_TOKEN_NOT_FOUND = 'REFRESH_TOKEN_NOT_FOUND';
    case REFRESH_TOKEN_EXPIRED = 'REFRESH_TOKEN_EXPIRED';
    case REFRESH_TOKEN_REVOKED = 'REFRESH_TOKEN_REVOKED';

    // CLIENT
    case INVALID_CLIENT_ID = 'INVALID_CLIENT_ID';
    case CLIENT_NOT_FOUND = 'CLIENT_NOT_FOUND';
    case DUPLICATED_CLIENT_NAME = 'DUPLICATED_CLIENT_NAME';
    case INVALID_CLIENT_NAME = 'INVALID_CLIENT_NAME';

    // CONTACT
    case INVALID_CONTACT_ID = 'INVALID_CONTACT_ID';
    case CONTACT_NOT_FOUND = 'CONTACT_NOT_FOUND';
    case INVALID_CONTACT_NAME = 'INVALID_CONTACT_NAME';

    // LINK
    case INVALID_LINK_ID = 'INVALID_LINK_ID';
    case LINK_NOT_FOUND = 'LINK_NOT_FOUND';
    case INVALID_LINK_URL = 'INVALID_LINK_URL';

    // PROJECT
    case INVALID_PROJECT_ID = 'INVALID_PROJECT_ID';
    case PROJECT_NOT_FOUND = 'PROJECT_NOT_FOUND';
    case DUPLICATED_PROJECT_NAME = 'DUPLICATED_PROJECT_NAME';
    case INVALID_PROJECT_NAME = 'INVALID_PROJECT_NAME';
    case INVALID_PROJECT_DATE_RANGE = 'INVALID_PROJECT_DATE_RANGE';

    // PROJECT_USER
    case INVALID_PROJECT_USER_ID = 'INVALID_PROJECT_USER_ID';
    case PROJECT_USER_NOT_FOUND = 'PROJECT_USER_NOT_FOUND';
    case DUPLICATED_PROJECT_USER = 'DUPLICATED_PROJECT_USER';
    case INVALID_PROJECT_USER_ALLOCATION = 'INVALID_PROJECT_USER_ALLOCATION';

    // TIME_ENTRY
    case INVALID_TIME_ENTRY_ID = 'INVALID_TIME_ENTRY_ID';
    case TIME_ENTRY_NOT_FOUND = 'TIME_ENTRY_NOT_FOUND';
    case INVALID_TIME_ENTRY_HOURS = 'INVALID_TIME_ENTRY_HOURS';
    case INVALID_TIME_ENTRY_DATE = 'INVALID_TIME_ENTRY_DATE';
}
